# Name of the speller package in various languages.
# The default is English + autonym:
[speller.name]
en = "Zulu spellchecker"
zu = "Autonym spellchecker"

# Description of the speller package in various languages.
# The default is English + autonym:
[speller.description]
en = "A spellchecker for Zulu, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"
zu = "TRANSLATE: A spellchecker for Zulu, made by members of the language community, and by the Divvun and Giellatekno groups at UiT The Arctic University of Norway"

[macos]
system_pkg_id = "no.divvun.MacDivvun.zu-x-exp"

[windows]
system_product_code = "{E205EF6C-4611-4A9D-B7C3-6C07548E8B94}_is1"
legacy_product_codes = [
    { value = "C28CEEFA-5BA5-40BD-B2D5-77D5A968665B", kind = "nsis" },
    { value = "B03EE16A-5372-492B-B672-D675C94C92B6", kind = "nsis" }
]
[package.speller]
name = "Zulu"
version = "0.1.1"

[package.grammar]
name = "Zulu"
version = "0.1.0"

[package.tts-text-proc]
name = "Zulu"
version = "0.1.0"
