template = "https://github.com/giellalt/template-lang-und"
rev_id = 253
template_sha = "5e69b0634aa0bd9773dece52e5b15d3003d605f1"

[replacements]
__GLOTTOLOG_ID__ = "zulu1248"
__REPO__ = "lang-zul-x-exp"
__UND2C__ = "zu"
__UNDEFINED__ = "Zulu"
__UND__ = "zul"
