template = "https://github.com/giellalt/template-lang-und"
rev_id = 279
template_sha = "7e1364a63ae8dd7a44d168dead7dc395b65c35a3"

[replacements]
__GLOTTOLOG_ID__ = "zulu1248"
__REPO__ = "lang-zul-x-exp"
__UND2C__ = "zu"
__UNDEFINED__ = "Zulu"
__UND__ = "zul"
