template = "https://github.com/giellalt/template-lang-und"
rev_id = 256
template_sha = "4e2ddf168a2aaf68d2c29db9e79e44e1dc4c2b76"

[replacements]
__GLOTTOLOG_ID__ = "zulu1248"
__REPO__ = "lang-zul-x-exp"
__UND2C__ = "zu"
__UNDEFINED__ = "Zulu"
__UND__ = "zul"
